# Generated by Django 3.2.5 on 2021-07-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'running'), (2, 'finished')], default=0),
        ),
    ]
